
import __ASTRO_IMAGE_IMPORT_2wmOh5 from "../images/books/artemis.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_Z13YRWi from "../images/books/fractal-noise.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_ZCMDMT from "../images/books/the-apollo-murders.webp?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_eEbYv from "../images/books/the-martian.webp?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_2wvDYU from "../images/books/the-rural-voter.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_2iXwEK from "../images/books/war.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_1jSaeL from "../images/books/other-significant-others.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json";
export default new Map([["../images/books/artemis.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json", __ASTRO_IMAGE_IMPORT_2wmOh5], ["../images/books/fractal-noise.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json", __ASTRO_IMAGE_IMPORT_Z13YRWi], ["../images/books/the-apollo-murders.webp?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json", __ASTRO_IMAGE_IMPORT_ZCMDMT], ["../images/books/the-martian.webp?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json", __ASTRO_IMAGE_IMPORT_eEbYv], ["../images/books/the-rural-voter.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json", __ASTRO_IMAGE_IMPORT_2wvDYU], ["../images/books/war.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json", __ASTRO_IMAGE_IMPORT_2iXwEK], ["../images/books/other-significant-others.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fjson%2Fbooks.json", __ASTRO_IMAGE_IMPORT_1jSaeL]]);
		