
import __ASTRO_IMAGE_IMPORT_ZYVnc0 from "../images/books/artemis.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_ZB6au8 from "../images/books/fractal-noise.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_2wHIDc from "../images/books/the-apollo-murders.webp?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_ZNjNEH from "../images/books/the-martian.webp?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_ZUrAU5 from "../images/books/the-rural-voter.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_2m6WsH from "../images/books/war.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_2kzqaO from "../images/books/other-significant-others.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_79g0X from "../images/books/frankenstein.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_LqUEM from "../images/books/as-i-walked-about.webp?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json";
import __ASTRO_IMAGE_IMPORT_Z1Vl1n9 from "../images/books/dead-wake.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json";
export default new Map([["../images/books/artemis.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json", __ASTRO_IMAGE_IMPORT_ZYVnc0], ["../images/books/fractal-noise.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json", __ASTRO_IMAGE_IMPORT_ZB6au8], ["../images/books/the-apollo-murders.webp?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json", __ASTRO_IMAGE_IMPORT_2wHIDc], ["../images/books/the-martian.webp?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json", __ASTRO_IMAGE_IMPORT_ZNjNEH], ["../images/books/the-rural-voter.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json", __ASTRO_IMAGE_IMPORT_ZUrAU5], ["../images/books/war.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json", __ASTRO_IMAGE_IMPORT_2m6WsH], ["../images/books/other-significant-others.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json", __ASTRO_IMAGE_IMPORT_2kzqaO], ["../images/books/frankenstein.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json", __ASTRO_IMAGE_IMPORT_79g0X], ["../images/books/as-i-walked-about.webp?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json", __ASTRO_IMAGE_IMPORT_LqUEM], ["../images/books/dead-wake.jpg?astroContentImageFlag=&importer=src%2Fdata%2Fbooks%2Fbooks.json", __ASTRO_IMAGE_IMPORT_Z1Vl1n9]]);
		